-- Torneos en su propia tabla (una fila por torneo) y resultados guardados de a partido.
--
-- Hasta acá todos los torneos de todos los organizadores vivían en una sola fila de app_data
-- ('sp:tournaments'): cada guardado reescribía la lista entera, y cada panel abierto la bajaba
-- entera cada 20 segundos. Además, dos celulares cargando resultados de la misma categoría a la vez
-- chocaban y uno de los dos resultados se perdía (la mezcla era por categoría).
--
-- Desde acá:
--   - torneos: una fila por torneo, con su versión (rev) y un resumen chico para la portada.
--   - guardar_torneo(p_torneo, p_rev, p_resumen): igual que antes (con versión), en la tabla nueva.
--   - guardar_partidos(p_torneo_id, p_cambios, p_rev_conocida, p_resumen): aplica solo lo que se
--     cargó en cada partido (sets, W.O., RET, en curso, horario) sobre la versión guardada. Dos
--     celulares cargando partidos distintos no chocan nunca.
--   - borrar_torneo, crear_inscripcion y aceptar_inscripcion usan la tabla nueva.
--   - restaurar_torneos(p_lista): reemplaza todos los torneos (respaldo; solo el creador).
--
-- TRANSICIÓN: mientras alguien tenga abierta la versión anterior de la app, la fila
-- app_data 'sp:tournaments' se sigue actualizando como espejo de la tabla (espejar_torneos). Se
-- saca con la migración siguiente, unos días después de publicar la app nueva.
--
-- Se corre una vez en Supabase > SQL Editor, ANTES de publicar la versión de la app que lo usa (la
-- versión anterior sigue funcionando igual con esto corrido). Vuelta atrás: al final del archivo.

-- ============================================================
-- Tabla
-- ============================================================

create table if not exists public.torneos (
  id text primary key,
  orden bigint generated by default as identity,       -- orden en que se crearon (el de la lista vieja)
  organizador_id uuid,                                  -- null: torneo informativo del creador
  datos jsonb not null,                                 -- el torneo completo, sin rev
  resumen jsonb,                                        -- lo que usa la portada (lo arma la app)
  rev int not null default 1,
  actualizado timestamptz not null default now()
);
create index if not exists torneos_por_organizador on public.torneos (organizador_id);

alter table public.torneos enable row level security;
revoke all on public.torneos from public, anon, authenticated;
grant select on public.torneos to anon, authenticated;
drop policy if exists "Torneos visibles para todos" on public.torneos;
create policy "Torneos visibles para todos" on public.torneos for select to public using (true);

-- Copia de la lista actual, en el mismo orden (solo si la tabla está vacía)
insert into public.torneos (id, orden, organizador_id, datos, rev)
select
  t.val->>'id',
  t.ord,
  case when coalesce(t.val->>'organizerId', '') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then (t.val->>'organizerId')::uuid end,
  t.val - 'rev',
  coalesce((t.val->>'rev')::int, 1)
from public.app_data a, jsonb_array_elements(a.value) with ordinality as t(val, ord)
where a.key = 'sp:tournaments'
  and coalesce(t.val->>'id', '') <> ''
  and not exists (select 1 from public.torneos)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.torneos', 'orden'), greatest((select coalesce(max(orden), 0) from public.torneos), 1));

-- ============================================================
-- Espejo para la versión anterior de la app (se saca en la migración siguiente)
-- ============================================================

create or replace function public.espejar_torneos()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Primero el bloqueo y después la lectura, en sentencias separadas: así la lista se arma con lo
  -- último que se guardó aunque dos torneos se guarden a la vez
  perform 1 from app_data where key = 'sp:tournaments' for update;
  update app_data
  set value = (select coalesce(jsonb_agg(datos || jsonb_build_object('rev', rev) order by orden), '[]'::jsonb) from torneos),
      updated_at = now()
  where key = 'sp:tournaments';
end;
$$;

-- ============================================================
-- Guardar un torneo entero (configuración, parejas, grupos, llave...)
-- ============================================================

drop function if exists public.guardar_torneo(jsonb, int);

create or replace function public.guardar_torneo(p_torneo jsonb, p_rev int, p_resumen jsonb default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actual torneos%rowtype;
  v_yo text := auth.uid()::text;
  v_creador boolean := public.es_creador();
  v_rev int;
begin
  if v_yo is null then
    raise exception 'no_autorizado';
  end if;
  if jsonb_typeof(p_torneo) <> 'object' or coalesce(p_torneo->>'id', '') = '' then
    raise exception 'datos_invalidos';
  end if;

  select * into v_actual from torneos where id = p_torneo->>'id' for update;

  if not found then
    -- Torneo nuevo: a nombre de quien lo crea (salvo el creador)
    if not v_creador and p_torneo->>'organizerId' is distinct from v_yo then
      raise exception 'no_autorizado';
    end if;
    insert into torneos (id, organizador_id, datos, resumen, rev)
    values (
      p_torneo->>'id',
      case when coalesce(p_torneo->>'organizerId', '') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then (p_torneo->>'organizerId')::uuid end,
      p_torneo - 'rev', p_resumen, 1
    );
    v_rev := 1;
  else
    -- Torneo existente: solo su organizador (y no puede pasárselo a otro), o el creador
    if not v_creador and (v_actual.datos->>'organizerId' is distinct from v_yo or p_torneo->>'organizerId' is distinct from v_yo) then
      raise exception 'no_autorizado';
    end if;
    if v_actual.rev <> coalesce(p_rev, 0) then
      return jsonb_build_object('estado', 'conflicto', 'torneo', v_actual.datos || jsonb_build_object('rev', v_actual.rev));
    end if;
    v_rev := v_actual.rev + 1;
    update torneos
    set datos = p_torneo - 'rev', resumen = coalesce(p_resumen, resumen), rev = v_rev, actualizado = now(),
        organizador_id = case when coalesce(p_torneo->>'organizerId', '') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then (p_torneo->>'organizerId')::uuid end
    where id = v_actual.id;
  end if;

  perform public.espejar_torneos();
  return jsonb_build_object('estado', 'ok', 'rev', v_rev);
end;
$$;

-- ============================================================
-- Guardar solo lo que se cargó en uno o más partidos
-- ============================================================
-- p_cambios: [{ "categoria": id, "partido": id, "cambios": { "sets": [...], "walkover": ..., ... } }]
-- Solo se aceptan sets, walkover, retired, liveStatus y schedule (lo demás se ignora). Un partido
-- que ya no existe (por ejemplo, otro celular rearmó la llave) se saltea y vuelve en "omitidos".
-- p_rev_conocida: la versión que tenía el celular. Si alguien más guardó en el medio, se devuelve
-- el torneo entero para que el celular quede al día.

create or replace function public.guardar_partidos(p_torneo_id text, p_cambios jsonb, p_rev_conocida int default null, p_resumen jsonb default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actual torneos%rowtype;
  v_datos jsonb;
  v_yo text := auth.uid()::text;
  v_cambio jsonb;
  v_ci int;
  v_path text[];
  v_clave text;
  v_omitidos jsonb := '[]'::jsonb;
  v_rev int;
  v_permitidas text[] := array['sets', 'walkover', 'retired', 'liveStatus', 'schedule'];
begin
  if v_yo is null then
    raise exception 'no_autorizado';
  end if;
  if jsonb_typeof(p_cambios) <> 'array' then
    raise exception 'datos_invalidos';
  end if;

  select * into v_actual from torneos where id = p_torneo_id for update;
  if not found then
    raise exception 'torneo_no_encontrado';
  end if;
  if not public.es_creador() and v_actual.datos->>'organizerId' is distinct from v_yo then
    raise exception 'no_autorizado';
  end if;

  v_datos := v_actual.datos;
  for v_cambio in select value from jsonb_array_elements(p_cambios) loop
    v_path := null;
    select c.ord - 1 into v_ci
    from jsonb_array_elements(coalesce(v_datos->'categories', '[]'::jsonb)) with ordinality as c(val, ord)
    where c.val->>'id' = v_cambio->>'categoria';

    if v_ci is not null then
      -- En los grupos
      select array['categories', v_ci::text, 'groups', (g.ord - 1)::text, 'matches', (m.ord - 1)::text] into v_path
      from jsonb_array_elements(coalesce(v_datos->'categories'->v_ci->'groups', '[]'::jsonb)) with ordinality as g(val, ord),
           jsonb_array_elements(coalesce(g.val->'matches', '[]'::jsonb)) with ordinality as m(val, ord)
      where m.val->>'id' = v_cambio->>'partido'
      limit 1;
      -- O en la llave
      if v_path is null and jsonb_typeof(v_datos->'categories'->v_ci->'bracket') = 'array' then
        select array['categories', v_ci::text, 'bracket', (r.ord - 1)::text, (m.ord - 1)::text] into v_path
        from jsonb_array_elements(v_datos->'categories'->v_ci->'bracket') with ordinality as r(val, ord),
             jsonb_array_elements(r.val) with ordinality as m(val, ord)
        where m.val->>'id' = v_cambio->>'partido'
        limit 1;
      end if;
    end if;

    if v_path is null then
      v_omitidos := v_omitidos || jsonb_build_array(v_cambio->>'partido');
      continue;
    end if;

    for v_clave in select jsonb_object_keys(coalesce(v_cambio->'cambios', '{}'::jsonb)) loop
      if v_clave = any(v_permitidas) then
        v_datos := jsonb_set(v_datos, v_path || v_clave, v_cambio->'cambios'->v_clave, true);
      end if;
    end loop;
  end loop;

  v_rev := v_actual.rev + 1;
  update torneos set datos = v_datos, resumen = coalesce(p_resumen, resumen), rev = v_rev, actualizado = now()
  where id = v_actual.id;
  perform public.espejar_torneos();

  return jsonb_build_object(
    'estado', 'ok',
    'rev', v_rev,
    'omitidos', v_omitidos,
    -- Si alguien más guardó desde la versión que tenía el celular, el torneo entero
    'torneo', case when p_rev_conocida is distinct from v_actual.rev then v_datos || jsonb_build_object('rev', v_rev) end
  );
end;
$$;

-- ============================================================
-- Borrar un torneo
-- ============================================================

create or replace function public.borrar_torneo(p_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actual torneos%rowtype;
  v_yo text := auth.uid()::text;
begin
  if v_yo is null then
    raise exception 'no_autorizado';
  end if;
  select * into v_actual from torneos where id = p_id for update;
  if not found then
    return jsonb_build_object('estado', 'ok'); -- ya no estaba
  end if;
  if not public.es_creador() and v_actual.datos->>'organizerId' is distinct from v_yo then
    raise exception 'no_autorizado';
  end if;
  delete from torneos where id = p_id;
  perform public.espejar_torneos();
  return jsonb_build_object('estado', 'ok');
end;
$$;

-- ============================================================
-- Restaurar un respaldo (solo el creador): reemplaza todos los torneos
-- ============================================================

create or replace function public.restaurar_torneos(p_lista jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.es_creador() then
    raise exception 'no_autorizado';
  end if;
  if jsonb_typeof(p_lista) <> 'array' then
    raise exception 'datos_invalidos';
  end if;
  delete from torneos;
  insert into torneos (id, orden, organizador_id, datos, rev)
  select
    t.val->>'id', t.ord,
    case when coalesce(t.val->>'organizerId', '') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then (t.val->>'organizerId')::uuid end,
    t.val - 'rev', coalesce((t.val->>'rev')::int, 0) + 1
  from jsonb_array_elements(p_lista) with ordinality as t(val, ord)
  where coalesce(t.val->>'id', '') <> ''
  on conflict (id) do nothing;
  perform setval(pg_get_serial_sequence('public.torneos', 'orden'), greatest((select coalesce(max(orden), 0) from torneos), 1));
  perform public.espejar_torneos();
  return jsonb_build_object('estado', 'ok');
end;
$$;

-- ============================================================
-- Inscripciones: igual que en 20260929 / 20261003, pero sobre la tabla nueva
-- ============================================================

create or replace function public.crear_inscripcion(
  p_torneo_id text,
  p_categoria_id text,
  p_jugador1 text,
  p_jugador2 text,
  p_telefono text,
  p_honeypot text default null,
  p_disponibilidad jsonb default null,
  p_cruce_mismo_dia boolean default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_torneo jsonb;
  v_categoria jsonb;
  v_formato text;
  v_cupo int;
  v_disp jsonb;
  v_j1 text := nullif(btrim(regexp_replace(coalesce(p_jugador1, ''), '\s+', ' ', 'g')), '');
  v_j2 text := nullif(btrim(regexp_replace(coalesce(p_jugador2, ''), '\s+', ' ', 'g')), '');
  v_tel text := public.normalizar_telefono_ar(p_telefono);
begin
  -- Honeypot: un bot lo completó. Se responde "ok" para no darle pistas, pero no se guarda nada.
  if coalesce(p_honeypot, '') <> '' then
    return 'ok';
  end if;

  select datos into v_torneo from torneos where id = p_torneo_id;

  if v_torneo is null
     or coalesce((v_torneo->>'inscripcionesAbiertas')::boolean, false) = false
     or v_torneo->>'status' = 'Finalizado'
     or coalesce((v_torneo->>'infoOnly')::boolean, false)
     or coalesce(v_torneo->>'organizerId', '') !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    raise exception 'inscripciones_cerradas';
  end if;

  select c.val into v_categoria from jsonb_array_elements(coalesce(v_torneo->'categories', '[]'::jsonb)) as c(val) where c.val->>'id' = p_categoria_id;
  if v_categoria is null then
    raise exception 'categoria_invalida';
  end if;

  v_formato := coalesce(v_categoria->>'format', 'zonas');
  -- Un Súper 8 con los partidos ya generados no admite más inscriptos
  if v_formato like 'super8%' and jsonb_array_length(coalesce(v_categoria->'groups', '[]'::jsonb)) > 0 then
    raise exception 'inscripciones_cerradas';
  end if;

  -- Súper 8 Individual: se anota un solo jugador. En el resto, los dos.
  if v_formato = 'super8_individual' then
    v_j2 := null;
  elsif v_j2 is null then
    raise exception 'datos_invalidos';
  end if;
  if v_j1 is null or char_length(v_j1) not between 3 and 80 or (v_j2 is not null and char_length(v_j2) not between 3 and 80) then
    raise exception 'datos_invalidos';
  end if;

  if v_tel is null then
    raise exception 'telefono_invalido';
  end if;

  -- Cupo por categoría: cuentan todas las parejas ya anotadas (a mano o aceptadas)
  v_cupo := case when v_formato like 'super8%' then 8 else nullif(v_categoria->>'cupo', '')::int end;
  if v_cupo is not null and jsonb_array_length(coalesce(v_categoria->'pairs', '[]'::jsonb)) >= v_cupo then
    raise exception 'cupo_completo';
  end if;

  -- Disponibilidad: solo se guardan días que el organizador cargó en el torneo, con horas válidas
  if p_disponibilidad is not null and jsonb_typeof(p_disponibilidad) = 'array' then
    select coalesce(jsonb_agg(jsonb_build_object('date', d->>'date', 'from', d->>'from', 'to', d->>'to') order by d->>'date'), '[]'::jsonb)
    into v_disp
    from jsonb_array_elements(p_disponibilidad) as d
    where d->>'date' in (select pd->>'date' from jsonb_array_elements(coalesce(v_torneo->'playDates', '[]'::jsonb)) as pd)
      and coalesce(d->>'from', '') ~ '^[0-9]{2}:[0-9]{2}$'
      and coalesce(d->>'to', '') ~ '^[0-9]{2}:[0-9]{2}$'
      and d->>'from' < d->>'to';
    if jsonb_array_length(v_disp) = 0 then
      raise exception 'disponibilidad_invalida';
    end if;
  end if;

  begin
    insert into inscripciones (torneo_id, organizador_id, categoria_id, jugador1_nombre, jugador2_nombre, telefono, disponibilidad, cruce_mismo_dia)
    values (p_torneo_id, (v_torneo->>'organizerId')::uuid, p_categoria_id, v_j1, v_j2, v_tel, v_disp, p_cruce_mismo_dia);
  exception when unique_violation then
    raise exception 'duplicada';
  end;

  return 'ok';
end;
$$;

create or replace function public.aceptar_inscripcion(p_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ins inscripciones%rowtype;
  v_actual torneos%rowtype;
  v_ci int;
  v_categoria jsonb;
  v_formato text;
  v_pareja jsonb;
begin
  select * into v_ins from inscripciones where id = p_id for update;
  if not found or v_ins.organizador_id is distinct from auth.uid() then
    raise exception 'no_autorizado';
  end if;
  if v_ins.estado <> 'pendiente' then
    raise exception 'ya_resuelta';
  end if;

  -- Se bloquea el torneo para que nadie lo cambie mientras se agrega la pareja
  select * into v_actual from torneos where id = v_ins.torneo_id and datos->>'organizerId' = auth.uid()::text for update;
  if not found then
    raise exception 'torneo_no_encontrado';
  end if;

  select c.ord - 1, c.val into v_ci, v_categoria
  from jsonb_array_elements(coalesce(v_actual.datos->'categories', '[]'::jsonb)) with ordinality as c(val, ord)
  where c.val->>'id' = v_ins.categoria_id;
  if v_ci is null then
    raise exception 'categoria_invalida';
  end if;

  v_formato := coalesce(v_categoria->>'format', 'zonas');
  if v_formato like 'super8%' then
    if jsonb_array_length(coalesce(v_categoria->'groups', '[]'::jsonb)) > 0 then
      raise exception 'partidos_generados';
    end if;
    if jsonb_array_length(coalesce(v_categoria->'pairs', '[]'::jsonb)) >= 8 then
      raise exception 'cupo_completo';
    end if;
  end if;

  -- Misma forma que una pareja cargada a mano. El teléfono NO se copia: los torneos son públicos.
  v_pareja := jsonb_build_object(
    'id', substr(md5(random()::text || clock_timestamp()::text), 1, 8),
    'name', case when v_ins.jugador2_nombre is null then v_ins.jugador1_nombre else v_ins.jugador1_nombre || ' / ' || v_ins.jugador2_nombre end,
    'availability', coalesce(v_ins.disponibilidad, '[]'::jsonb),
    'inscripcionId', v_ins.id
  );
  if v_ins.cruce_mismo_dia is not null then
    v_pareja := v_pareja || jsonb_build_object('sameDayBracket', v_ins.cruce_mismo_dia);
  end if;

  update torneos
  set datos = jsonb_set(datos, array['categories', v_ci::text, 'pairs'], coalesce(v_categoria->'pairs', '[]'::jsonb) || jsonb_build_array(v_pareja)),
      rev = rev + 1, actualizado = now()
  where id = v_actual.id;
  perform public.espejar_torneos();

  update inscripciones set estado = 'aceptada', pareja_id = v_pareja->>'id', resuelta_at = now() where id = p_id;
  return v_pareja;
end;
$$;

-- ============================================================
-- Permisos
-- ============================================================

revoke all on function public.espejar_torneos() from public, anon, authenticated;
revoke all on function public.guardar_torneo(jsonb, int, jsonb) from public, anon, authenticated;
revoke all on function public.guardar_partidos(text, jsonb, int, jsonb) from public, anon, authenticated;
revoke all on function public.borrar_torneo(text) from public, anon, authenticated;
revoke all on function public.restaurar_torneos(jsonb) from public, anon, authenticated;
revoke all on function public.crear_inscripcion(text, text, text, text, text, text, jsonb, boolean) from public, anon, authenticated;
revoke all on function public.aceptar_inscripcion(uuid) from public, anon, authenticated;

grant execute on function public.guardar_torneo(jsonb, int, jsonb) to authenticated;
grant execute on function public.guardar_partidos(text, jsonb, int, jsonb) to authenticated;
grant execute on function public.borrar_torneo(text) to authenticated;
grant execute on function public.restaurar_torneos(jsonb) to authenticated;
grant execute on function public.crear_inscripcion(text, text, text, text, text, text, jsonb, boolean) to anon, authenticated;
grant execute on function public.aceptar_inscripcion(uuid) to authenticated;

-- ============================================================
-- Vuelta atrás (solo si hiciera falta, ANTES de la migración siguiente; la lista vieja quedó al
-- día gracias al espejo). En este orden:
--   1. drop function if exists public.guardar_torneo(jsonb, int, jsonb);
--      drop function if exists public.guardar_partidos(text, jsonb, int, jsonb);
--      drop function if exists public.restaurar_torneos(jsonb);
--   2. Volver a correr 20261003_guardar_torneo.sql y 20260929_inscripciones_disponibilidad.sql
--      (vuelven guardar_torneo, borrar_torneo, aceptar_inscripcion y crear_inscripcion sobre la lista).
--   3. drop function if exists public.espejar_torneos();
--      drop table if exists public.torneos;
-- ============================================================
